(function(){var c=null;function g(a){if(a!=c)return escape(a.toString());return""}function h(a){if(a!=c)return a.toString().substring(0,256);return""}function j(a,b){var f=g(b);if(f!=""){var d=g(a);if(d!="")return"&".concat(d,"=",f)}return""}function k(a){var b=typeof a;if(a==c||b=="object"||b=="function")return c;return String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function l(a){var b;a=a.google_custom_params;if(!a||typeof a!="object"||a instanceof Array)b="";else{var f=[];for(b in a){var d=a[b];if(d instanceof Array){for(var e=[],i=0;i<d.length;++i){var q=k(d[i]);q!=c&&e.push(q)}d=e.length==0?c:e.join(",")}else d=k(d);(e=k(b))&&d!=c&&f.push(e+"="+d)}b=f.join(";")}if(b=="")return"";return"&".concat("data=",encodeURIComponent(b))}function m(a){if(typeof a!="number"&&typeof a!="string")return"";return g(a.toString())}
function n(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],f=0,d=a.length;f<d;f++){var e=a[f],i=[];e&&(i.push(m(e.value)),i.push(m(e.quantity)),i.push(m(e.item_id)),i.push(m(e.adwords_grouping)),i.push(m(e.sku)),b.push("("+i.join("*")+")"))}return b.length>0?"&item="+b.join(""):""}
function o(a,b,f){var d=[];if(a){var e=a.screen;e&&(d.push(j("u_h",e.height)),d.push(j("u_w",e.width)),d.push(j("u_ah",e.availHeight)),d.push(j("u_aw",e.availWidth)),d.push(j("u_cd",e.colorDepth)));a.history&&d.push(j("u_his",a.history.length))}f&&typeof f.getTimezoneOffset=="function"&&d.push(j("u_tz",-f.getTimezoneOffset()));b&&(typeof b.javaEnabled=="function"&&d.push(j("u_java",b.javaEnabled())),b.plugins&&d.push(j("u_nplug",b.plugins.length)),b.mimeTypes&&d.push(j("u_nmime",b.mimeTypes.length)));
return d.join("")}function p(a,b){var f="";if(b){var d=b.referrer;if(a&&a.top&&b.location&&a.top.location==b.location)f+=j("ref",h(d)),d=b.location;f+=j("url",h(d))}return f}function r(a){if(a&&a.location&&a.location.protocol&&a.location.protocol.toString().toLowerCase()=="https:")return"https:";return"http:"}function s(a){if(a.google_remarketing_only)return"googleads.g.doubleclick.net";return a.google_conversion_domain||"www.googleadservices.com"}
function t(a,b,f){var d="/?";a.google_conversion_type=="landing"&&(d="/extclk?");var e;e=a.google_remarketing_only?"viewthroughconversion/":"conversion/";d=r(a)+"//"+s(a)+"/pagead/"+[e,g(a.google_conversion_id),d,"random=",g(a.google_conversion_time)].join("");a:{e=a.google_conversion_language;if(e!=c){e=e.toString();if(2==e.length){e=j("hl",e);break a}if(5==e.length){e=j("hl",e.substring(0,2))+j("gl",e.substring(3,5));break a}}e=""}d+=[j("cv",a.google_conversion_js_version),j("fst",a.google_conversion_first_time),
j("num",a.google_conversion_snippets),j("fmt",a.google_conversion_format),j("value",a.google_conversion_value),j("label",a.google_conversion_label),j("oid",a.google_conversion_order_id),j("bg",a.google_conversion_color),e,j("guid","ON"),j("disvt",a.google_disable_viewthrough),n(a),o(a,b,a.google_conversion_date),p(a,f),l(a)].join("");return d}
function u(a){if({ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a])return a+".html";return"en_US.html"}
function v(a,b,f){b=t(a,b,f);f=function(a,b,f){return'<img height="'+f+'" width="'+b+'" border="0" src="'+a+'" />'};return a.google_conversion_format==0&&a.google_conversion_domain==c?'<a href="'+(r(a)+"//services.google.com/sitestats/"+u(a.google_conversion_language)+"?cid="+g(a.google_conversion_id))+'" target="_blank">'+f(b,135,27)+"</a>":a.google_conversion_snippets>1||a.google_conversion_format==3?f(b,1,1):'<iframe name="google_conversion_frame" width="'+(a.google_conversion_format==2?200:300)+
'" height="'+(a.google_conversion_format==2?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+f(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"};var w=window;
if(w)if(/[\?&;]google_debug/.exec(document.URL)!=c){var x=document.getElementsByTagName("head")[0];x||(x=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(x,document.getElementsByTagName("body")[0]));var y=document.createElement("script");y.src=r(window)+"//"+s(window)+"/pagead/conversion_debug_overlay.js";x.appendChild(y)}else{try{var z;w.google_conversion_type=="landing"||!w.google_conversion_id?z=!1:w.google_remarketing_only&&w.google_disable_viewthrough?z=!1:
(w.google_conversion_date=new Date,w.google_conversion_time=w.google_conversion_date.getTime(),typeof w.google_conversion_snippets=="number"&&w.google_conversion_snippets>0?w.google_conversion_snippets+=1:w.google_conversion_snippets=1,typeof w.google_conversion_first_time!="number"&&(w.google_conversion_first_time=w.google_conversion_time),w.google_conversion_js_version="6",w.google_conversion_format!=0&&w.google_conversion_format!=1&&w.google_conversion_format!=2&&w.google_conversion_format!=3&&
(w.google_conversion_format=1),z=!0);z&&document.write(v(w,navigator,document))}catch(A){}w.google_conversion_date=c;w.google_conversion_time=c;w.google_conversion_js_version=c;w.google_conversion_id=c;w.google_conversion_value=c;w.google_conversion_label=c;w.google_conversion_language=c;w.google_conversion_format=c;w.google_conversion_color=c;w.google_conversion_type=c;w.google_conversion_order_id=c;w.google_conversion_items=c;w.google_custom_params=c;w.google_conversion_domain=c;w.google_disable_viewthrough=
c;w.google_remarketing_only=c};})();